---
- name: Start a Redis service
  become: true
  community.docker.docker_swarm_service:
    name: redis-cluster
    image: redis
    mode: global
    publish:
      - published_port: 6379
        target_port: 6379

- name: Get Swarm cluster information
  become: true
  community.docker.docker_swarm_info:
    services: yes
    nodes: yes
  register: swarm_info

- name: Set facts about the cluster
  ansible.builtin.set_fact:
    swarm_info: "{{ swarm_info }}"
    cacheable: true
